baseURL: https://demo.gethugothemes.com/educenter/examplesite/
title: MER 30th @EDUCU

theme: educenter-hugo
paginate: '6'
summaryLength: '10'
disqusShortname: []
disableLanguages: []
params:
  address: คณะครุศาสตร์ จุฬาลงกรณ์มหาวิทยาลัย 254 ถนนพญาไท แขวงวังใหม่ เขตปทุมวัน กรุงเทพฯ 10330
  author: KruRoo@EDUCU
  contact_form_action: '#'
  cookies:
    enable: no
    expire_days: 2
  description: การประชุมสัมมนาทางวิชาการ การวัดผล การประเมิน และวิจัยสัมพันธ์แห่งประเทศไทย
  email: mer30th.cu@gmail.com
  google_analitycs_id: ''
  logo: images/logo2.png
  map:
    enable: no
    gmap_api: https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places
    map_latitude: '51.5223477'
    map_longitude: '-0.1622023'
    map_marker: images/marker.png
  mobile: ''
  plugins:
    css:
      - link: plugins/bootstrap/bootstrap.min.css
      - link: plugins/slick/slick.css
      - link: plugins/animate/animate.css
      - link: plugins/venobox/venobox.css
      - link: plugins/themify-icons/themify-icons.css
    js:
      - link: plugins/jQuery/jquery.min.js
      - link: plugins/bootstrap/bootstrap.min.js
      - link: plugins/slick/slick.min.js
      - link: plugins/venobox/venobox.min.js
      - link: plugins/filterizr/jquery.filterizr.min.js
      - link: plugins/google-map/gmap.js
  preloader:
    enable: yes
    preloader: images/flame2.gif
  social:

      
  subscription:
    enable: no
    mailchimp_form_action: https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074
    mailchimp_form_name: b_463ee871f45d2d93748e77cad_a0a2c6d074
  top_header: no
Languages:
  en:
    contentDir: content/english
    copyright: Copyright &copy; 2023 [Faculty of Education, Chulalongkorn University](https://www.facebook.com/KruRooEduCU)
    home: Home
    languageCode: en-us
    languageName: En
    menu:
     
      main:
          
        - name: About MER 30th
          url: about/
          weight: 5

        - hasChildren: yes
          name: Register
          weight: 1
          
        - name: สำหรับผู้เข้าร่วมการประชุม
          parent: Register
          url: about/register_attend
          weight: 3
          
        - name: สำหรับผู้นำเสนอผลงาน
          parent: Register
          url: about/register_present
          weight: 2       

        - name: สมัครหลักสูตร Preconference
          parent: Register
          url: course
          weight: 4
          
   #     - hasChildren: yes
  #        name: Activities
  #        weight: 4
          
  #      - name: Presentation Sessions
  #        parent: Activities
  #        url: research/
  #        weight: 2

  #      - name: Preconference Workshops
  #        parent: Activities
  #        url: course/  
  #        weight: 3
          
          

          



  
